### Idle configuration

set $resumecommand 'fnottctl list | grep "idle\$" | cut -d : -f 1 | xargs -r -n 1 -- fnottctl dismiss'

exec_always pkill swayidle
exec_always swayidle -w \
     timeout 60 'notify-send -i dialog-information -u low -t 59999 "idle" "Obacht\nUntätigkeit Stufe 1"' resume $resumecommand \
    timeout 120 'notify-send -i dialog-warning -u normal -t 54999 "idle" "Letzte Ermahnung!\nUntätigkeit Stufe 2"' resume $resumecommand \
    timeout 175 'notify-send -i dialog-warning -u critical -t 4999 "idle" "Allerletzte Ermahnung!\nUntätigkeit Stufe 3"' resume $resumecommand \
    timeout 180 '/usr/local/bin/swaylock -f -c 333355' \
    timeout 300 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
    before-sleep '/usr/local/bin/swaylock -f -c 335533'
