#? keyboard layout
bindsym $mod+i input type:keyboard xkb_switch_layout next
bindsym $mod+Shift+i input type:keyboard xkb_switch_layout prev

#? experimental
bindsym $mod+y input type:tablet_pad map_to_output *
bindsym $mod+$ctrl+y exec $swayhelper_rs command input type:tablet_pad map_to_region @fw.x@ @fw.y@ @fw.w@ @fw.h@
bindsym $mod+$alt+y exec swaymsg input type:tablet_pad map_to_region $(slurp -f "%x %y %w %h")

# consider disabled_on_external_mouse,disabled
#? toggle touchpad
bindsym XF86TouchpadToggle input type:touchpad events toggle enabled disabled
