#
# Scratchpad:
#
# Sway has a "scratchpad", which is a bag of holding for windows.
# You can send windows there and get them back later.

#? Move the currently focused window to the scratchpad
bindsym $mod+Shift+minus exec sway-helper.sh scratch_move
# , move scratchpad, border normal 5

#? Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
bindsym $mod+minus scratchpad show

#? restore from scratchpad
bindsym $mod+$ctrl+minus exec sway-helper.sh scratch_restore regular

#? restore window from scratchpad (selection with wofi)
bindsym $mod+$alt+minus exec sway-helper.sh scratch_list regular

#? swap selected window with selected scratchpad window
bindsym $mod+$alt+Shift+minus exec sway-helper.sh scratch_list swap

