bindsym $mod+$alt+p mode "Passthrough (mod-alt-p to exit)"

#? start passthrough mode (e.g. for nested sessions). fun fact: does not work in nested session
mode "Passthrough (mod-alt-p to exit)" {
    bindsym $mod+$alt+p mode "default"
}
