bar {
    swaybar_command /usr/local/bin/waybar
    mode dock
    position top
    id bar-0
}

bar bar-1 {
    swaybar_command /bin/true
    mode hide
    modifier none
    hidden_state hide
}

#? toggle visibility of side bar
bindsym $mod+$ctrl+b bar bar-1 hidden_state toggle
bindsym $mod+$ctrl+$shift+b bar bar-0 mode toggle

