set $dd_id QuakeDD
set $dd $term --app-id $dd_id
set $dd_resize resize set 100ppt 40ppt, move position 0 0

for_window [app_id="$dd_id"] floating enable, $dd_resize, move to scratchpad, scratchpad show

#? toggle QuakeDD terminal
bindsym $mod+Grave exec swaymsg '[app_id="$dd_id"] scratchpad show' || $dd && sleep .1 && swaymsg '[app_id="$dd_id"] $dd_resize'

set $dd_ht_id QuakeTop
set $dd_ht $term --app-id $dd_ht_id htop

#? toggle QuakeDD htop
for_window [app_id="$dd_ht_id"] floating enable, $dd_resize, move to scratchpad, scratchpad show

bindsym $mod+$shift+Grave exec swaymsg '[app_id="$dd_ht_id"] scratchpad show' || $dd_ht && sleep .1 && swaymsg '[app_id="$dd_ht_id"] $dd_resize'
