set $swayimgf_id swayimg-frame
set $swayimgf ~/Progs/src.untracked/swayimg/build/swayimg -a $swayimgf_id ~/Sync0/Sync/Bilder/Frame-Rotation --slideshow -o random -c viewer.slideshow_time=20 -c viewer.position=center -c viewer.window=#55555555 -c info.viewer.top_left=name\,imagesize\,exif -c keys.viewer.i="info viewer" -c keys.viewer.Shift+i="info off" -c info.show=no -c info.info_timeout=10
set $swayimgf_resize resize set 20ppt 20ppt

# this sets the new window
for_window [app_id="$swayimgf_id"] border none, sticky enable, mark --add _newstickychange, mark --add _newnodeco, floating enable, $swayimgf_resize, move to scratchpad, scratchpad show, exec 'sleep .1 && swayhelper move_window_to_corner 9 --app_id swayimg-frame

# this adjusts the existing window OR starts a new one, but that one is covered by the above
#? toggle image frame
bindsym $mod+$ctrl+i exec swaymsg '[app_id="$swayimgf_id"] scratchpad show' || $swayimgf && sleep .1 && swaymsg '[app_id="$swayimgf_id"] $swayimgf_resize' && sleep .1 && swayhelper move_window_to_corner 9 --app_id swayimg-frame

# and once more for restarts. can't use pkill.
# this is not ideal, because it'll ignore the gaps initially.
exec_always swaymsg '[app_id="$swayimgf_id"] move to scratchpad, scratchpad show' || $swayimgf && sleep .1 && swaymsg '[app_id="$swayimgf_id"] $swayimgf_resize' && sleep .1 && swayhelper move_window_to_corner 9 --app_id swayimg-frame

