exec exec fnott
exec exec /usr/bin/lxpolkit
exec exec /usr/bin/blueman-applet

# Bielefeld
exec exec wlsunset -l 52.0 -L 8.5

#FIXME: record pid and control via pid
exec_always pkill sov
exec_always "rm -f /run/user/$(id -u)/sovpipe && mkfifo /run/user/$(id -u)/sovpipe && tail -f /run/user/$(id -u)/sovpipe | sov"

#FIXME: record pid and control via pid
exec_always pkill swayhelper
exec_always swayhelper daemon --floating-tags --border-tags --sticky-tags --transparency "[con_mark=\"_transp_*\"] opacity 0.75; [con_id=\"__focused__\" con_mark=\"_transp_*\"] opacity 1.0; [app_id=\"foot\" con_id=\"__focused__\" con_mark=\"_transp_*\"] opacity 0.9" "[con_mark=\"_transp_*\"] opacity 0.75" --mode-change-notifications

